server:
  port: ${PORT:8081}
  servlet:
    context-path: ${CONTEXT-PATH:/state-service}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_PORT:4041}