server:
  port: ${PORT:8080}
  servlet:
    context-path: ${CONTEXT_PATH:/country-service}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
  server:
    port: ${MANAGEMENT_PORT:4040}