server:
    port: ${PORT:8080}
    servlet:
        context-path: ${CONTEXT-PATH:/country-service}

client:
    state:
        url: http://${STATE_SERVICE_HOST:localhost:8081}/state-service/api/v1/states?code=

management:
    endpoints:
        web:
            exposure:
                include: '*'
